export enum Permission {
  CreateAdminUser = 'CREATE_ADMIN_USER',
  CreateDevice = 'CREATE_DEVICE',
  CreateDeviceCategory = 'CREATE_DEVICE_CATEGORY',
  CreateDeviceModel = 'CREATE_DEVICE_MODEL',
  CreateReading = 'CREATE_READING',
  GetCategories = 'GET_CATEGORIES',
  GetDeviceById = 'GET_DEVICE_BY_ID',
  GetModelsByCategory = 'GET_MODELS_BY_CATEGORY',
  AddDevice = 'ADD_DEVICE',
  GetUser = 'GET_USER',
  DeleteUser = 'DELETE_USER',
  UpdateUser = 'UPDATE_USER',
  GetAllUserDevices = 'GET_ALL_USER_DEVICES',
  RemoveUserDevice = 'REMOVE_USER_DEVICE',
  UpdateUserDevice = 'UPDATE_USER_DEVICE',
  UploadFile = 'UPLOAD_FILE',
}
